/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    NotFoundResponse,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
} from '../models';

/**
 * 
 */
export class TranslationsApi extends runtime.BaseAPI {

    /**
     * This is based off of a hard-coded list pulled from the CRM currently. This will hopefully be a call to the CRM itself in the future
     * Get the list of companies
     */
    async getTranslationsCompaniesRaw(): Promise<runtime.ApiResponse<Array<object>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // jwt authentication
        }

        const response = await this.request({
            path: `/translations/companies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * This is based off of a hard-coded list pulled from the CRM currently. This will hopefully be a call to the CRM itself in the future
     * Get the list of companies
     */
    async getTranslationsCompanies(): Promise<Array<object>> {
        const response = await this.getTranslationsCompaniesRaw();
        return await response.value();
    }

}
