/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Company,
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddUserModel
 */
export interface AddUserModel {
    /**
     * 
     * @type {string}
     * @memberof AddUserModel
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserModel
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserModel
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserModel
     */
    permissionLevel: AddUserModelPermissionLevelEnum;
    /**
     * 
     * @type {Company}
     * @memberof AddUserModel
     */
    company: Company;
    /**
     * 
     * @type {string}
     * @memberof AddUserModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserModel
     */
    phone: string;
}

export function AddUserModelFromJSON(json: any): AddUserModel {
    return AddUserModelFromJSONTyped(json, false);
}

export function AddUserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'username': json['username'],
        'permissionLevel': json['permissionLevel'],
        'company': CompanyFromJSON(json['company']),
        'email': json['email'],
        'phone': json['phone'],
    };
}

export function AddUserModelToJSON(value?: AddUserModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'username': value.username,
        'permissionLevel': value.permissionLevel,
        'company': CompanyToJSON(value.company),
        'email': value.email,
        'phone': value.phone,
    };
}

/**
* @export
* @enum {string}
*/
export enum AddUserModelPermissionLevelEnum {
    USER = 'USER',
    SUPER = 'SUPER',
    ADMIN = 'ADMIN'
}


