/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    cOMPANYNAME?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    cADENCEID?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    tMWCODE?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    wPCRMID?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    sHIPTO?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    aDDRESSLINE1?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    aDDRESSLINE2?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    cITY?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    sTATE?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    zIP?: string;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cOMPANYNAME': !exists(json, 'COMPANY NAME') ? undefined : json['COMPANY NAME'],
        'cADENCEID': !exists(json, 'CADENCE ID') ? undefined : json['CADENCE ID'],
        'tMWCODE': !exists(json, 'TMW CODE') ? undefined : json['TMW CODE'],
        'wPCRMID': !exists(json, 'WP CRM ID') ? undefined : json['WP CRM ID'],
        'sHIPTO': !exists(json, 'SHIP TO') ? undefined : json['SHIP TO'],
        'aDDRESSLINE1': !exists(json, 'ADDRESS LINE 1') ? undefined : json['ADDRESS LINE 1'],
        'aDDRESSLINE2': !exists(json, 'ADDRESS LINE 2') ? undefined : json['ADDRESS LINE 2'],
        'cITY': !exists(json, 'CITY') ? undefined : json['CITY'],
        'sTATE': !exists(json, 'STATE') ? undefined : json['STATE'],
        'zIP': !exists(json, 'ZIP') ? undefined : json['ZIP'],
    };
}

export function CompanyToJSON(value?: Company | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'COMPANY NAME': value.cOMPANYNAME,
        'CADENCE ID': value.cADENCEID,
        'TMW CODE': value.tMWCODE,
        'WP CRM ID': value.wPCRMID,
        'SHIP TO': value.sHIPTO,
        'ADDRESS LINE 1': value.aDDRESSLINE1,
        'ADDRESS LINE 2': value.aDDRESSLINE2,
        'CITY': value.cITY,
        'STATE': value.sTATE,
        'ZIP': value.zIP,
    };
}


