/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model4
 */
export interface Model4 {
    /**
     * 
     * @type {Array<string>}
     * @memberof Model4
     */
    tmwCodes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model4
     */
    pickupRange?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Model4
     */
    compare?: boolean;
}

export function Model4FromJSON(json: any): Model4 {
    return Model4FromJSONTyped(json, false);
}

export function Model4FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model4 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tmwCodes': !exists(json, 'tmwCodes') ? undefined : json['tmwCodes'],
        'pickupRange': !exists(json, 'pickupRange') ? undefined : json['pickupRange'],
        'compare': !exists(json, 'compare') ? undefined : json['compare'],
    };
}

export function Model4ToJSON(value?: Model4 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tmwCodes': value.tmwCodes,
        'pickupRange': value.pickupRange,
        'compare': value.compare,
    };
}


