/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PickupRange,
    PickupRangeFromJSON,
    PickupRangeFromJSONTyped,
    PickupRangeToJSON,
} from './';

/**
 * 
 * @export
 * @interface Model5
 */
export interface Model5 {
    /**
     * 
     * @type {Array<string>}
     * @memberof Model5
     */
    rangeResult?: Array<string>;
    /**
     * 
     * @type {PickupRange}
     * @memberof Model5
     */
    pickupRange?: PickupRange;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model5
     */
    compareResult?: Array<string>;
    /**
     * 
     * @type {PickupRange}
     * @memberof Model5
     */
    compareRange?: PickupRange;
}

export function Model5FromJSON(json: any): Model5 {
    return Model5FromJSONTyped(json, false);
}

export function Model5FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model5 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rangeResult': !exists(json, 'rangeResult') ? undefined : json['rangeResult'],
        'pickupRange': !exists(json, 'pickupRange') ? undefined : PickupRangeFromJSON(json['pickupRange']),
        'compareResult': !exists(json, 'compareResult') ? undefined : json['compareResult'],
        'compareRange': !exists(json, 'compareRange') ? undefined : PickupRangeFromJSON(json['compareRange']),
    };
}

export function Model5ToJSON(value?: Model5 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rangeResult': value.rangeResult,
        'pickupRange': PickupRangeToJSON(value.pickupRange),
        'compareResult': value.compareResult,
        'compareRange': PickupRangeToJSON(value.compareRange),
    };
}


