/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DateRange,
    DateRangeFromJSON,
    DateRangeFromJSONTyped,
    DateRangeToJSON,
} from './';

/**
 * 
 * @export
 * @interface Model5
 */
export interface Model5 {
    /**
     * 
     * @type {Array<string>}
     * @memberof Model5
     */
    rangeResult?: Array<string>;
    /**
     * 
     * @type {DateRange}
     * @memberof Model5
     */
    dateRange?: DateRange;
}

export function Model5FromJSON(json: any): Model5 {
    return Model5FromJSONTyped(json, false);
}

export function Model5FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model5 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rangeResult': !exists(json, 'rangeResult') ? undefined : json['rangeResult'],
        'dateRange': !exists(json, 'dateRange') ? undefined : DateRangeFromJSON(json['dateRange']),
    };
}

export function Model5ToJSON(value?: Model5 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rangeResult': value.rangeResult,
        'dateRange': DateRangeToJSON(value.dateRange),
    };
}


