/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model2
 */
export interface Model2 {
    /**
     * 
     * @type {Array<string>}
     * @memberof Model2
     */
    tmwCodes?: Array<string>;
}

export function Model2FromJSON(json: any): Model2 {
    return Model2FromJSONTyped(json, false);
}

export function Model2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tmwCodes': !exists(json, 'tmwCodes') ? undefined : json['tmwCodes'],
    };
}

export function Model2ToJSON(value?: Model2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tmwCodes': value.tmwCodes,
    };
}


