/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model3
 */
export interface Model3 {
    /**
     * 
     * @type {Array<string>}
     * @memberof Model3
     */
    tmwCodes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Model3
     */
    pickup?: string;
}

export function Model3FromJSON(json: any): Model3 {
    return Model3FromJSONTyped(json, false);
}

export function Model3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model3 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tmwCodes': !exists(json, 'tmwCodes') ? undefined : json['tmwCodes'],
        'pickup': !exists(json, 'pickup') ? undefined : json['pickup'],
    };
}

export function Model3ToJSON(value?: Model3 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tmwCodes': value.tmwCodes,
        'pickup': value.pickup,
    };
}


