/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model1
 */
export interface Model1 {
    /**
     * 
     * @type {string}
     * @memberof Model1
     */
    token?: string;
    /**
     * 
     * @type {object}
     * @memberof Model1
     */
    verification?: object;
}

export function Model1FromJSON(json: any): Model1 {
    return Model1FromJSONTyped(json, false);
}

export function Model1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'verification': !exists(json, 'verification') ? undefined : json['verification'],
    };
}

export function Model1ToJSON(value?: Model1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'verification': value.verification,
    };
}


