/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotFoundResponse
 */
export interface NotFoundResponse {
    /**
     * 
     * @type {number}
     * @memberof NotFoundResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof NotFoundResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof NotFoundResponse
     */
    message?: string;
}

export function NotFoundResponseFromJSON(json: any): NotFoundResponse {
    return NotFoundResponseFromJSONTyped(json, false);
}

export function NotFoundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function NotFoundResponseToJSON(value?: NotFoundResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCode': value.statusCode,
        'error': value.error,
        'message': value.message,
    };
}


