/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetModel
 */
export interface PasswordResetModel {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetModel
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetModel
     */
    newPassword?: string;
}

export function PasswordResetModelFromJSON(json: any): PasswordResetModel {
    return PasswordResetModelFromJSONTyped(json, false);
}

export function PasswordResetModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
    };
}

export function PasswordResetModelToJSON(value?: PasswordResetModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'newPassword': value.newPassword,
    };
}


