/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpModel
 */
export interface SignUpModel {
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    confirmPassword: string;
}

export function SignUpModelFromJSON(json: any): SignUpModel {
    return SignUpModelFromJSONTyped(json, false);
}

export function SignUpModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
    };
}

export function SignUpModelToJSON(value?: SignUpModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'confirmPassword': value.confirmPassword,
    };
}


