/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Company,
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserJson
 */
export interface UserJson {
    /**
     * 
     * @type {string}
     * @memberof UserJson
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJson
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJson
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJson
     */
    permissionLevel?: string;
    /**
     * 
     * @type {Company}
     * @memberof UserJson
     */
    company: Company;
    /**
     * 
     * @type {boolean}
     * @memberof UserJson
     */
    needsNewPassword?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserJson
     */
    tmwCodes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserJson
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserJson
     */
    phone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserJson
     */
    verified?: boolean;
}

export function UserJsonFromJSON(json: any): UserJson {
    return UserJsonFromJSONTyped(json, false);
}

export function UserJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserJson {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'permissionLevel': !exists(json, 'permissionLevel') ? undefined : json['permissionLevel'],
        'company': CompanyFromJSON(json['company']),
        'needsNewPassword': !exists(json, 'needsNewPassword') ? undefined : json['needsNewPassword'],
        'tmwCodes': !exists(json, 'tmw_codes') ? undefined : json['tmw_codes'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
    };
}

export function UserJsonToJSON(value?: UserJson | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'username': value.username,
        'permissionLevel': value.permissionLevel,
        'company': CompanyToJSON(value.company),
        'needsNewPassword': value.needsNewPassword,
        'tmw_codes': value.tmwCodes,
        'email': value.email,
        'phone': value.phone,
        'verified': value.verified,
    };
}


