/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerificationCodeModel
 */
export interface VerificationCodeModel {
    /**
     * 
     * @type {string}
     * @memberof VerificationCodeModel
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof VerificationCodeModel
     */
    phone: string;
}

export function VerificationCodeModelFromJSON(json: any): VerificationCodeModel {
    return VerificationCodeModelFromJSONTyped(json, false);
}

export function VerificationCodeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationCodeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'phone': json['phone'],
    };
}

export function VerificationCodeModelToJSON(value?: VerificationCodeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'phone': value.phone,
    };
}


