/* tslint:disable */
/* eslint-disable */
/**
 * FST Data Access API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoiceVerificationRequestModel
 */
export interface VoiceVerificationRequestModel {
    /**
     * 
     * @type {string}
     * @memberof VoiceVerificationRequestModel
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof VoiceVerificationRequestModel
     */
    phone?: string;
}

export function VoiceVerificationRequestModelFromJSON(json: any): VoiceVerificationRequestModel {
    return VoiceVerificationRequestModelFromJSONTyped(json, false);
}

export function VoiceVerificationRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoiceVerificationRequestModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function VoiceVerificationRequestModelToJSON(value?: VoiceVerificationRequestModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'phone': value.phone,
    };
}


